### ISSUE TITLE
geopandas dependency causes Windows test failures

### ISSUE THREAD

**Issue by hhtong** [dwave-examples/graph-coloring#12]
#8 introduced the geopandas dependency. To successfully install geopandas with pip on windows, we have to first install its dependencies. See warning here: https://geopandas.org/getting_started/install.html#installing-with-pip.

Proposed solution: #11

**Comment by vgoliber** [comment]
@arcondello : can we close this issue? The proposed solution #11 was merged.

**Comment by arcondello** [comment]
Then I believe so, yes
